"""empty message

Revision ID: 1b14b20b0f1d
Revises: 
Create Date: 2022-07-07 21:24:05.477931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b14b20b0f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.String(length=11), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('senha', sa.String(length=50), nullable=True),
    sa.Column('turno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(length=11), nullable=True),
    sa.Column('validade', sa.String(), nullable=True),
    sa.Column('responsavel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('saída',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(length=11), nullable=True),
    sa.Column('validade', sa.String(length=50), nullable=True),
    sa.Column('responsavel', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['responsavel'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saída')
    op.drop_table('entrada')
    op.drop_table('funcionario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
