"""empty message

Revision ID: 1b9f9a3550ab
Revises: 
Create Date: 2022-07-07 16:27:37.830046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9f9a3550ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saída',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(length=11), nullable=True),
    sa.Column('validade', sa.String(length=50), nullable=True),
    sa.Column('responsavel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saída')
    # ### end Alembic commands ###
